version: '3.8'
services:
  gradio-app:
    build: .
    ports:
      - "7860:7860"
    env_file:
      - .env
    environment:
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
